#include "rcc.h"

void rcc_config(void)
{
	/*Sysclock = 168MHz*/
	while (!READ_BIT(RCC->CR, RCC_CR_HSIRDY));
	SET_BIT(RCC->CR, RCC_CR_HSEON);
	while (!READ_BIT(RCC->CR, RCC_CR_HSERDY));
	SET_BIT(RCC->APB1ENR, RCC_APB1ENR_PWREN);
	/*5ms flash latency for 168Mhz sysclock*/
	MODIFY_REG(FLASH->ACR, FLASH_ACR_LATENCY, FLASH_ACR_LATENCY_5WS << FLASH_ACR_LATENCY_Pos);
	/*PLL config*/
	CLEAR_BIT(RCC->CR, RCC_CR_PLLON);
	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLSRC, RCC_PLLCFGR_PLLSRC_HSE);
	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLQ, 7<<RCC_PLLCFGR_PLLQ_Pos);
	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLP, 0xb00<<RCC_PLLCFGR_PLLP_Pos);
	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLN, 168<<RCC_PLLCFGR_PLLN_Pos);
	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLM, 4<<RCC_PLLCFGR_PLLM_Pos);

	MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE1, RCC_CFGR_PPRE1_DIV4);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE2, RCC_CFGR_PPRE2_DIV2);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_HPRE, RCC_CFGR_HPRE_DIV1);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_SW, RCC_CFGR_SW_PLL);

	SET_BIT(RCC->CR, RCC_CR_PLLON);

	while (READ_BIT(RCC->CR, RCC_CR_PLLRDY) == RESET);

	SystemCoreClockUpdate();

}

